### ISSUE TITLE
Zuweisungen für Divisions und Organizations einbauen/anpassen

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#1187]
Herausgezogen aus #945 

TODOs:
- [x] Divisions in der Datenlogik 'assignable' machen
- [x] Automatisierte Zuweisung: beim der Erstellung wird die Division anhand ihrer Welt entweder dem Team 'Family' oder 'Refugees' zugewiesen. Der Absender der Zuweisung ist der Ersteller der Division. Message TBD.. z.B. 'Bitte die Family-Angebote aufnehmen'
- [x] Folgende Topic-Optionen einer Zuweisung sollen für die Divisions hinzukommen (naming TBD): Aktualisierung, Wiedervorlage, Crawler, ext. Feedback & Neu
- [x] Die GenericForms müssen so angepasst werden, dass für ein assignable Model automatisch der AssignableContainer darum (bzw. in der UI darüber) ausgerendert wird
- [x] Dieser Container delegiert das mayEdit/disabled flag an alle ChildComponents (Form Elemente werden disabled wenn der Nutzer das Objekt nicht editieren darf, weil er/sie nicht zugewiesen ist)
- [x] Die AssignableActions müssen um die Auswahl des Topics erweitert werden, damit der Nutzer die Möglichkeit hat, das Topic entsprechend anzupassen
- [x] Es gibt einen extra 'als erledigt markieren'-Button bei der Division, der eine separate Operation auslöst (setzt done auf true und weist die Divison dem SystemUser zu)
- [x] Es gibt einen extra 'als unvollständig markieren'-Button (wording TBD) bei der Division, der den done-state zurücksetzt
- [x] Bestandsdaten: analog zu ihren Organisationen
- [x] Bestandsdaten: Divisions von all_done-Orgas werden mit done=true erstellt und dem System zugewiesen

Orga's:
- [x] Organizations assignable machen & die GenericForms ggf. anpassen
- [x] Automatisierung/Seiteneffekt: Wenn eine Orga auf all_done gesetzt wird, wird sie automatisch dem Systemuser zugewiesen
- [x] Automatisierung/Seiteneffekt: Wenn eine Division einem Nutzer zugewiesen wird, wird diesem Nutzer automatisch die dazugehörige Orga zugewiesen, wenn diese im state initialized ist und sie gerade dem system-user zugewiesen ist
- [x] Automatisierung/Seiteneffekt: Wenn eine Division auf done gesetzt wird und damit alle aktuell vorhandenen Divisons der Orga done sind, wird auch die Orga von approved auf all_done gesetzt. Analog soll eine all_done Orga automatisch wieder zurück in approved wechseln, wenn ihr eine neue Divison (die per Definition nicht done ist) hinzugefügt wird.
- [x] Bestandsdaten: initialized & completed => creator wird zugewiesen, all_done => system, restliche states => Screening

Zu klären (mit Screening):
- [ ] Wem werden 'Bestandsdaten' (auch automatisiert erstellte) zugewiesen? Ein paar Gedanken: Grundsätzlich können wir versuchen, anhand der Daten der Orga (created_ & approved_by) nachträglich Zuweisungen für die automatisch angelegten Divisions zu erstellen. Wie viele und welche hängt dann von der finalen Automatisierungslogik ab.

Nice to have/sinnvolle Erweiterungen der Zuweisungen
- [x] Assignment-History: man kann sich von jedem Assignable Model die Zuweisungs-Geschichte angucken. Da wir für jede Kleinigkeit eine neue Zuweisung erstellen dürfte das relativ fix mit einer nach Datum sortierten Liste der Zuweisungen des Models zu erledigen sein. Dann kann man besser nachvollziehen, was wann mit dem Model passiert ist.
- [ ] Grafik/UserInteraction-Overhaul des AssignableContainers
- [ ] Sub-Assignments: im Moment gibt es nur die Root/Haupt-Assignments. In der Datenbank ist aber schon vorgesehen, dass es auch Sub-Assignments gibt. Darüber könnte man z.B. Nachfragen der Übersetzer abhandeln. 

@Twiek Fällt dir noch was ein?

**Comment by NilsVollmer** [comment]
Deploy TODO (nachdem die Divisions nachträglich automatisch angelegt wurden - am besten in das 945 Issue übertragen, sobald das Issue hier in den Branch gemerged wurde):
```ruby
# create assignments for divisions
Division.find_each do |div|
# TODO
end
```
